import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import JSZip from 'jszip';
import { supabase, supabaseEnabled } from './lib_supabase';

const STORAGE_KEY = 'scenario-editor-project-v01';
const USER_KEY = 'scenario-editor-user-v01';

const uid = (prefix = 'id') => `${prefix}_${Math.random().toString(36).slice(2, 9)}${Date.now().toString(36).slice(-5)}`;

function starterProject() {
  const sus = uid('char');
  const min = uid('char');
  const s1 = uid('scene');
  const s2 = uid('scene');
  const e1 = uid('ending');
  return {
    id: uid('project'),
    name: '새 시나리오',
    characters: [
      { id: sus, name: '수연' },
      { id: min, name: '민지' },
    ],
    scenes: [
      {
        id: s1,
        name: 'Scene 01',
        blocks: [
          { id: uid('line'), type: 'dialogue', speakerId: sus, text: '오늘은 어디로 갈까?' },
          { id: uid('line'), type: 'dialogue', speakerId: min, text: '나는 카페에 가고 싶어.' },
          { id: uid('choice'), type: 'choice', prompt: '어디로 갈까?', options: [
            { id: uid('opt'), text: '카페에 간다', targetId: s2 },
            { id: uid('opt'), text: '집에 간다', targetId: s1 },
            { id: uid('opt'), text: '민지를 따라간다', targetId: e1 },
          ] },
        ],
      },
      {
        id: s2,
        name: 'Scene 02',
        blocks: [
          { id: uid('line'), type: 'dialogue', speakerId: sus, text: '좋아. 카페로 가자.' },
          { id: uid('line'), type: 'dialogue', speakerId: min, text: '응, 잠깐만.' },
          { id: uid('line'), type: 'dialogue', speakerId: null, text: '두 사람은 천천히 카페 쪽으로 걸어갔다.' },
        ],
      },
    ],
    endings: [
      { id: e1, name: 'BAD END 01', body: '민지를 따라간 결과, 예상하지 못했던 일이 벌어졌다.' },
    ],
  };
}

function normalizeProject(raw) {
  const fallback = starterProject();
  if (!raw || typeof raw !== 'object') return fallback;
  return {
    ...fallback,
    ...raw,
    id: raw.id || fallback.id,
    name: raw.name || '새 시나리오',
    characters: Array.isArray(raw.characters) ? raw.characters : [],
    scenes: Array.isArray(raw.scenes) ? raw.scenes : [],
    endings: Array.isArray(raw.endings) ? raw.endings : [],
  };
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function downloadText(text, filename, type = 'text/plain;charset=utf-8') {
  downloadBlob(new Blob([text], { type }), filename);
}

function sceneKey(id) {
  return `SCENE_${String(id).replace(/[^a-zA-Z0-9]/g, '_').toUpperCase()}`;
}

function endingKey(id) {
  return `ENDING_${String(id).replace(/[^a-zA-Z0-9]/g, '_').toUpperCase()}`;
}

function makeInk(project) {
  const lines = [
    `// Generated by Scenario Editor`,
    `// Project: ${project.name}`,
    ``,
    `-> ${project.scenes[0] ? sceneKey(project.scenes[0].id) : 'END'}`,
    ``,
  ];

  for (const scene of project.scenes) {
    lines.push(`=== ${sceneKey(scene.id)} ===`);
    for (const block of scene.blocks) {
      if (block.type === 'dialogue') {
        const speaker = project.characters.find(c => c.id === block.speakerId);
        if (speaker) lines.push(`~ speaker = "${escapeInk(speaker.name)}"`);
        else lines.push(`~ speaker = ""`);
        lines.push(`${escapeInk(block.text)}`);
      } else if (block.type === 'choice') {
        if (block.prompt?.trim()) {
          lines.push(`// CHOICE: ${escapeInk(block.prompt)}`);
        }
        for (const option of block.options || []) {
          lines.push(`* ${escapeInk(option.text || '선택지')}`);
          const target = project.scenes.find(s => s.id === option.targetId);
          const ending = project.endings.find(e => e.id === option.targetId);
          lines.push(`    -> ${target ? sceneKey(target.id) : ending ? endingKey(ending.id) : sceneKey(scene.id)}`);
        }
      }
    }
    lines.push(`-> END`);
    lines.push(``);
  }

  for (const ending of project.endings) {
    lines.push(`=== ${endingKey(ending.id)} ===`);
    if (ending.body?.trim()) lines.push(escapeInk(ending.body));
    lines.push(`-> END`);
    lines.push(``);
  }
  return lines.join('\n');
}

function escapeInk(text = '') {
  return String(text).replace(/\\/g, '\\\\');
}

function makeJson(project) {
  return JSON.stringify({
    format: 'scenario-editor-v1',
    exportedAt: new Date().toISOString(),
    project,
  }, null, 2);
}

function makeCharactersJson(project) {
  return JSON.stringify(project.characters, null, 2);
}

async function exportUnity(project) {
  const zip = new JSZip();
  zip.file('scenario.ink', makeInk(project));
  zip.file('scenario.json', makeJson(project));
  zip.file('characters.json', makeCharactersJson(project));
  zip.file('README_Unity.txt', `Scenario Editor export\n\n1. scenario.ink is the story source.\n2. With the official ink Unity integration installed, Unity imports and compiles .ink files automatically.\n3. scenario.json is the editor-native backup/data file.\n4. characters.json contains character IDs and display names.\n\nGenerated from: ${project.name}\n`);
  const blob = await zip.generateAsync({ type: 'blob' });
  downloadBlob(blob, `${safeName(project.name)}_UnityExport.zip`);
}

function safeName(name) {
  return String(name || 'scenario').replace(/[\\/:*?"<>|]/g, '_').trim() || 'scenario';
}

function AuthBox({ user, onUserChange, onRefresh }) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');

  const signIn = async (mode) => {
    if (!supabaseEnabled) return;
    setBusy(true);
    setMessage('');
    try {
      const result = mode === 'signup'
        ? await supabase.auth.signUp({ email, password })
        : await supabase.auth.signInWithPassword({ email, password });
      if (result.error) throw result.error;
      setMessage(mode === 'signup' ? '가입 요청을 보냈어. 이메일 확인이 필요한 설정이라면 메일도 확인해줘.' : '로그인 완료!');
      await onRefresh();
    } catch (error) {
      setMessage(error.message || '인증 중 오류가 발생했어.');
    } finally {
      setBusy(false);
    }
  };

  const signOut = async () => {
    if (!supabase) return;
    await supabase.auth.signOut();
    onUserChange(null);
    onRefresh();
  };

  if (!supabaseEnabled) {
    return (
      <div className="cloud-card muted">
        <div className="tiny-label">CLOUD SYNC</div>
        <strong>현재는 로컬 모드</strong>
        <p>Supabase 연결 전에도 편집/미리보기/export는 모두 사용할 수 있어.</p>
      </div>
    );
  }

  if (user) {
    return (
      <div className="cloud-card">
        <div className="tiny-label">CLOUD SYNC</div>
        <strong>{user.email}</strong>
        <p>이 프로젝트는 로그인한 계정에 저장돼.</p>
        <button className="ghost-btn full" onClick={signOut}>로그아웃</button>
      </div>
    );
  }

  return (
    <div className="cloud-card">
      <div className="tiny-label">CLOUD SYNC</div>
      <strong>PC ↔ 모바일 동기화</strong>
      <p>같은 계정으로 로그인하면 프로젝트를 불러올 수 있어.</p>
      <input className="auth-input" placeholder="이메일" value={email} onChange={e => setEmail(e.target.value)} />
      <input className="auth-input" type="password" placeholder="비밀번호" value={password} onChange={e => setPassword(e.target.value)} />
      <div className="auth-actions">
        <button className="dark-btn" disabled={busy} onClick={() => signIn('signin')}>로그인</button>
        <button className="ghost-btn" disabled={busy} onClick={() => signIn('signup')}>회원가입</button>
      </div>
      {message && <div className="tiny-message">{message}</div>}
    </div>
  );
}

function App() {
  const [project, setProject] = useState(() => {
    try {
      return normalizeProject(JSON.parse(localStorage.getItem(STORAGE_KEY)));
    } catch {
      return starterProject();
    }
  });
  const [selectedSceneId, setSelectedSceneId] = useState(() => {
    try {
      const saved = normalizeProject(JSON.parse(localStorage.getItem(STORAGE_KEY)));
      return saved.scenes[0]?.id;
    } catch { return null; }
  });
  const [selectedTab, setSelectedTab] = useState('script');
  const [user, setUser] = useState(null);
  const [status, setStatus] = useState('저장됨');
  const [previewMode, setPreviewMode] = useState(false);
  const [previewSceneId, setPreviewSceneId] = useState(null);
  const [previewBlockIndex, setPreviewBlockIndex] = useState(0);
  const [previewEndingId, setPreviewEndingId] = useState(null);
  const [newChar, setNewChar] = useState('');
  const [newScene, setNewScene] = useState('');
  const [newEnding, setNewEnding] = useState('');
  const dialogueRefs = useRef({});
  const saveTimer = useRef(null);

  const currentScene = useMemo(
    () => project.scenes.find(scene => scene.id === selectedSceneId) || project.scenes[0],
    [project.scenes, selectedSceneId]
  );

  const persistLocal = useCallback((next) => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
  }, []);

  const persistCloud = useCallback(async (next) => {
    if (!supabase || !user) return;
    clearTimeout(saveTimer.current);
    setStatus('클라우드 저장 중…');
    saveTimer.current = setTimeout(async () => {
      try {
        const payload = { id: next.id, user_id: user.id, name: next.name, data: next };
        const { error } = await supabase.from('projects').upsert(payload, { onConflict: 'id' });
        if (error) throw error;
        setStatus('클라우드 저장됨');
      } catch (error) {
        console.error(error);
        setStatus('로컬 저장됨 · 클라우드 실패');
      }
    }, 700);
  }, [user]);

  const updateProject = useCallback((updater) => {
    setProject(prev => {
      const next = typeof updater === 'function' ? updater(prev) : updater;
      persistLocal(next);
      persistCloud(next);
      setStatus('저장됨');
      return next;
    });
  }, [persistLocal, persistCloud]);

  const loadCloud = useCallback(async (currentUser) => {
    if (!supabase || !currentUser) return;
    try {
      const { data, error } = await supabase.from('projects').select('*').order('updated_at', { ascending: false }).limit(1);
      if (error) throw error;
      if (data?.[0]?.data) {
        const next = normalizeProject(data[0].data);
        setProject(next);
        persistLocal(next);
        setSelectedSceneId(next.scenes[0]?.id || null);
        setStatus('클라우드에서 불러옴');
      } else {
        const next = project;
        await supabase.from('projects').insert({ id: next.id, user_id: currentUser.id, name: next.name, data: next });
      }
    } catch (error) {
      console.error(error);
      setStatus('클라우드 불러오기 실패 · 로컬 사용 중');
    }
  }, [persistLocal, project]);

  const refreshAuth = useCallback(async () => {
    if (!supabase) return;
    const { data } = await supabase.auth.getUser();
    setUser(data?.user || null);
    if (data?.user) await loadCloud(data.user);
  }, [loadCloud]);

  useEffect(() => {
    if (!supabase) return undefined;
    refreshAuth();
    const { data: subscription } = supabase.auth.onAuthStateChange((_event, session) => {
      const nextUser = session?.user || null;
      setUser(nextUser);
    });
    return () => subscription.subscription.unsubscribe();
  }, [refreshAuth]);

  useEffect(() => {
    if (!selectedSceneId && project.scenes[0]) setSelectedSceneId(project.scenes[0].id);
  }, [project.scenes, selectedSceneId]);

  const updateScene = (sceneId, updater) => {
    updateProject(p => ({
      ...p,
      scenes: p.scenes.map(s => s.id === sceneId ? (typeof updater === 'function' ? updater(s) : updater) : s),
    }));
  };

  const addDialogueAfter = (sceneId, index, speakerId = null) => {
    const newId = uid('line');
    updateScene(sceneId, scene => {
      const blocks = [...scene.blocks];
      blocks.splice(index + 1, 0, { id: newId, type: 'dialogue', speakerId, text: '' });
      return { ...scene, blocks };
    });
    requestAnimationFrame(() => {
      dialogueRefs.current[newId]?.focus();
    });
  };

  const handleDialogueKeyDown = (event, sceneId, block, index) => {
    if (event.key !== 'Tab' || event.shiftKey || event.ctrlKey || event.metaKey || event.altKey) return;
    event.preventDefault();
    addDialogueAfter(sceneId, index, block.speakerId || null);
  };

  const updateBlock = (sceneId, blockId, updater) => {
    updateScene(sceneId, scene => ({
      ...scene,
      blocks: scene.blocks.map(block => block.id === blockId ? (typeof updater === 'function' ? updater(block) : updater) : block),
    }));
  };

  const deleteBlock = (sceneId, blockId) => {
    updateScene(sceneId, scene => ({ ...scene, blocks: scene.blocks.filter(block => block.id !== blockId) }));
  };

  const addCharacter = () => {
    const name = newChar.trim();
    if (!name) return;
    updateProject(p => ({ ...p, characters: [...p.characters, { id: uid('char'), name }] }));
    setNewChar('');
  };

  const addScene = () => {
    const name = newScene.trim() || `Scene ${String(project.scenes.length + 1).padStart(2, '0')}`;
    const scene = { id: uid('scene'), name, blocks: [{ id: uid('line'), type: 'dialogue', speakerId: project.characters[0]?.id || null, text: '' }] };
    updateProject(p => ({ ...p, scenes: [...p.scenes, scene] }));
    setSelectedSceneId(scene.id);
    setNewScene('');
    setSelectedTab('script');
  };

  const addEnding = () => {
    const name = newEnding.trim() || `BAD END ${String(project.endings.length + 1).padStart(2, '0')}`;
    const ending = { id: uid('ending'), name, body: '' };
    updateProject(p => ({ ...p, endings: [...p.endings, ending] }));
    setNewEnding('');
    setSelectedTab('endings');
  };

  const deleteScene = (sceneId) => {
    if (project.scenes.length <= 1) return;
    const nextScenes = project.scenes.filter(scene => scene.id !== sceneId);
    updateProject(p => ({ ...p, scenes: nextScenes }));
    if (selectedSceneId === sceneId) setSelectedSceneId(nextScenes[0].id);
  };

  const importProject = (event) => {
    const file = event.target.files?.[0];
    event.target.value = '';
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      try {
        const raw = JSON.parse(reader.result);
        const next = normalizeProject(raw.project || raw);
        updateProject(next);
        setSelectedSceneId(next.scenes[0]?.id || null);
        setStatus('불러옴');
      } catch {
        alert('JSON 형식의 프로젝트 파일을 읽지 못했어.');
      }
    };
    reader.readAsText(file);
  };

  const startPreview = () => {
    setPreviewMode(true);
    setPreviewSceneId(project.scenes[0]?.id || null);
    setPreviewBlockIndex(0);
    setPreviewEndingId(null);
  };

  const previewScene = project.scenes.find(s => s.id === previewSceneId);
  const previewBlock = previewScene?.blocks?.[previewBlockIndex];

  const goPreviewNext = (targetId) => {
    const targetScene = project.scenes.find(s => s.id === targetId);
    const targetEnding = project.endings.find(e => e.id === targetId);
    if (targetScene) {
      setPreviewSceneId(targetScene.id);
      setPreviewBlockIndex(0);
      return;
    }
    if (targetEnding) {
      setPreviewSceneId(null);
      setPreviewBlockIndex(-1);
      setPreviewEndingId(targetEnding.id);
    }
  };

  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="brand">
          <div className="brand-mark">S</div>
          <div>
            <div className="brand-title">Scenario Editor</div>
            <div className="brand-sub">visual novel writing tool</div>
          </div>
        </div>

        <div className="sidebar-section">
          <div className="section-heading">PROJECT</div>
          <input className="project-name-input" value={project.name} onChange={e => updateProject(p => ({ ...p, name: e.target.value }))} />
        </div>

        <div className="sidebar-section grow">
          <div className="section-row">
            <div className="section-heading">SCENES</div>
            <button className="mini-add" title="씬 추가" onClick={addScene}>＋</button>
          </div>
          <div className="nav-list">
            {project.scenes.map((scene, i) => (
              <button key={scene.id} className={`nav-item ${selectedTab === 'script' && selectedSceneId === scene.id ? 'active' : ''}`} onClick={() => { setSelectedTab('script'); setSelectedSceneId(scene.id); }}>
                <span className="nav-index">{String(i + 1).padStart(2, '0')}</span>
                <span>{scene.name}</span>
              </button>
            ))}
          </div>

          <div className="section-row ending-head">
            <div className="section-heading">ENDINGS</div>
            <button className="mini-add" title="엔딩 추가" onClick={addEnding}>＋</button>
          </div>
          <div className="nav-list">
            {project.endings.map(ending => (
              <button key={ending.id} className={`nav-item ${selectedTab === 'endings' && selectedSceneId === ending.id ? 'active' : ''}`} onClick={() => { setSelectedTab('endings'); setSelectedSceneId(ending.id); }}>
                <span className="ending-dot">●</span>
                <span>{ending.name}</span>
              </button>
            ))}
          </div>

          <button className={`nav-item nav-tab ${selectedTab === 'characters' ? 'active' : ''}`} onClick={() => setSelectedTab('characters')}>
            <span className="nav-icon">✦</span>
            <span>등장인물</span>
          </button>
        </div>

        <div className="sidebar-bottom">
          <AuthBox user={user} onUserChange={setUser} onRefresh={refreshAuth} />
          <div className="save-status"><span className="status-dot" />{status}</div>
        </div>
      </aside>

      <main className="main-area">
        <header className="topbar">
          <div className="topbar-left">
            <span className="crumb">{selectedTab === 'script' ? currentScene?.name : selectedTab === 'characters' ? '등장인물' : selectedTab === 'endings' ? '엔딩' : '미리보기'}</span>
            <span className="slash">/</span>
            <span className="muted-text">{project.name}</span>
          </div>
          <div className="topbar-actions">
            <label className="ghost-btn import-btn">JSON 불러오기<input type="file" accept="application/json,.json" hidden onChange={importProject} /></label>
            <button className="ghost-btn" onClick={() => downloadText(makeJson(project), `${safeName(project.name)}.json`, 'application/json;charset=utf-8')}>JSON 저장</button>
            <button className="ghost-btn" onClick={() => downloadText(makeInk(project), `${safeName(project.name)}.ink`)}>INK 저장</button>
            <button className="dark-btn" onClick={() => exportUnity(project)}>Unity Export .zip</button>
            <button className="preview-btn" onClick={startPreview}>▶ 미리보기</button>
          </div>
        </header>

        <div className="content-wrap">
          {selectedTab === 'script' && currentScene && (
            <section className="editor-card">
              <div className="editor-header">
                <div>
                  <input className="scene-title-input" value={currentScene.name} onChange={e => updateScene(currentScene.id, s => ({ ...s, name: e.target.value }))} />
                  <div className="editor-hint">대사칸에서 <kbd>Tab</kbd> → 다음 행 생성 + 이전 캐릭터 자동 상속</div>
                </div>
                <button className="danger-text-btn" onClick={() => deleteScene(currentScene.id)} disabled={project.scenes.length <= 1}>씬 삭제</button>
              </div>

              <div className="script-table">
                <div className="table-head">
                  <div className="speaker-head">CHARACTER</div>
                  <div>DIALOGUE</div>
                  <div className="table-actions-head" />
                </div>
                <div className="block-list">
                  {currentScene.blocks.map((block, index) => block.type === 'dialogue' ? (
                    <div className="script-row" key={block.id}>
                      <div className="speaker-cell">
                        <select
                          value={block.speakerId || ''}
                          onChange={e => updateBlock(currentScene.id, block.id, b => ({ ...b, speakerId: e.target.value || null }))}
                        >
                          <option value="">(독백)</option>
                          {project.characters.map(character => <option key={character.id} value={character.id}>{character.name}</option>)}
                        </select>
                      </div>
                      <textarea
                        ref={el => { dialogueRefs.current[block.id] = el; }}
                        className="dialogue-cell"
                        value={block.text}
                        placeholder="대사를 입력하세요…"
                        onChange={e => updateBlock(currentScene.id, block.id, b => ({ ...b, text: e.target.value }))}
                        onKeyDown={e => handleDialogueKeyDown(e, currentScene.id, block, index)}
                        rows={1}
                      />
                      <div className="row-actions">
                        <button title="위로" onClick={() => {
                          if (index === 0) return;
                          updateScene(currentScene.id, scene => {
                            const blocks = [...scene.blocks];
                            [blocks[index - 1], blocks[index]] = [blocks[index], blocks[index - 1]];
                            return { ...scene, blocks };
                          });
                        }}>↑</button>
                        <button title="아래로" onClick={() => {
                          if (index === currentScene.blocks.length - 1) return;
                          updateScene(currentScene.id, scene => {
                            const blocks = [...scene.blocks];
                            [blocks[index + 1], blocks[index]] = [blocks[index], blocks[index + 1]];
                            return { ...scene, blocks };
                          });
                        }}>↓</button>
                        <button title="삭제" onClick={() => deleteBlock(currentScene.id, block.id)}>×</button>
                      </div>
                    </div>
                  ) : (
                    <div className="choice-block" key={block.id}>
                      <div className="choice-title-row">
                        <div className="choice-label">CHOICE</div>
                        <input className="choice-prompt" value={block.prompt || ''} placeholder="선택지 앞에 표시할 안내문 (선택)" onChange={e => updateBlock(currentScene.id, block.id, b => ({ ...b, prompt: e.target.value }))} />
                        <button className="row-delete" onClick={() => deleteBlock(currentScene.id, block.id)}>×</button>
                      </div>
                      <div className="options-list">
                        {(block.options || []).map((option, optionIndex) => (
                          <div className="option-row" key={option.id}>
                            <span className="option-number">{optionIndex + 1}</span>
                            <input value={option.text} placeholder="선택지" onChange={e => updateBlock(currentScene.id, block.id, b => ({ ...b, options: b.options.map(o => o.id === option.id ? { ...o, text: e.target.value } : o) }))} />
                            <span className="arrow">→</span>
                            <select value={option.targetId || ''} onChange={e => updateBlock(currentScene.id, block.id, b => ({ ...b, options: b.options.map(o => o.id === option.id ? { ...o, targetId: e.target.value } : o) }))}>
                              <option value="">대상 선택</option>
                              <optgroup label="Scenes">
                                {project.scenes.map(scene => <option key={scene.id} value={scene.id}>{scene.name}</option>)}
                              </optgroup>
                              <optgroup label="Endings">
                                {project.endings.map(ending => <option key={ending.id} value={ending.id}>{ending.name}</option>)}
                              </optgroup>
                            </select>
                            <button className="row-delete" onClick={() => updateBlock(currentScene.id, block.id, b => ({ ...b, options: b.options.filter(o => o.id !== option.id) }))}>×</button>
                          </div>
                        ))}
                      </div>
                      <button className="add-option-btn" onClick={() => updateBlock(currentScene.id, block.id, b => ({ ...b, options: [...(b.options || []), { id: uid('opt'), text: '', targetId: '' }] }))}>＋ 선택지 추가</button>
                    </div>
                  ))}
                </div>
              </div>

              <div className="editor-footer-actions">
                <button className="add-dialogue-btn" onClick={() => addDialogueAfter(currentScene.id, currentScene.blocks.length - 1, currentScene.blocks.at(-1)?.type === 'dialogue' ? currentScene.blocks.at(-1).speakerId : null)}>＋ 대사</button>
                <button className="add-choice-btn" onClick={() => updateScene(currentScene.id, scene => ({ ...scene, blocks: [...scene.blocks, { id: uid('choice'), type: 'choice', prompt: '', options: [{ id: uid('opt'), text: '', targetId: '' }] }] }))}>＋ 선택지</button>
              </div>
            </section>
          )}

          {selectedTab === 'characters' && (
            <section className="library-card">
              <div className="library-header">
                <div>
                  <div className="eyebrow">CHARACTER LIBRARY</div>
                  <h1>등장인물</h1>
                  <p>여기에 한 번 등록해두면 대본의 왼쪽 칸에서 바로 선택할 수 있어.</p>
                </div>
                <div className="inline-form">
                  <input value={newChar} onChange={e => setNewChar(e.target.value)} placeholder="캐릭터 이름" onKeyDown={e => e.key === 'Enter' && addCharacter()} />
                  <button className="dark-btn" onClick={addCharacter}>캐릭터 추가</button>
                </div>
              </div>
              <div className="character-grid">
                {project.characters.map(character => (
                  <div className="character-card" key={character.id}>
                    <div className="character-avatar">{character.name.slice(0, 1)}</div>
                    <input value={character.name} onChange={e => updateProject(p => ({ ...p, characters: p.characters.map(c => c.id === character.id ? { ...c, name: e.target.value } : c) }))} />
                    <button className="row-delete" onClick={() => updateProject(p => ({ ...p, characters: p.characters.filter(c => c.id !== character.id), scenes: p.scenes.map(s => ({ ...s, blocks: s.blocks.map(b => b.type === 'dialogue' && b.speakerId === character.id ? { ...b, speakerId: null } : b) })) }))}>삭제</button>
                  </div>
                ))}
                {project.characters.length === 0 && <div className="empty-state">등록된 캐릭터가 없어.</div>}
              </div>
            </section>
          )}

          {selectedTab === 'endings' && (
            <section className="library-card">
              <div className="library-header">
                <div>
                  <div className="eyebrow">ENDING LIBRARY</div>
                  <h1>엔딩 관리</h1>
                  <p>배드 엔딩이 수십 개가 되어도 여기서 독립적으로 관리할 수 있어.</p>
                </div>
                <div className="inline-form">
                  <input value={newEnding} onChange={e => setNewEnding(e.target.value)} placeholder="엔딩 이름" onKeyDown={e => e.key === 'Enter' && addEnding()} />
                  <button className="dark-btn" onClick={addEnding}>엔딩 추가</button>
                </div>
              </div>
              <div className="ending-grid">
                {project.endings.map((ending, index) => (
                  <div className="ending-editor" key={ending.id}>
                    <div className="ending-top">
                      <span className="ending-tag">BAD END {String(index + 1).padStart(2, '0')}</span>
                      <button className="row-delete" onClick={() => updateProject(p => ({ ...p, endings: p.endings.filter(e => e.id !== ending.id), scenes: p.scenes.map(s => ({ ...s, blocks: s.blocks.map(b => b.type === 'choice' ? { ...b, options: b.options.map(o => o.targetId === ending.id ? { ...o, targetId: '' } : o) } : b) })) }))}>×</button>
                    </div>
                    <input className="ending-name-input" value={ending.name} onChange={e => updateProject(p => ({ ...p, endings: p.endings.map(x => x.id === ending.id ? { ...x, name: e.target.value } : x) }))} />
                    <textarea className="ending-body-input" value={ending.body} placeholder="엔딩 내용을 입력하세요…" onChange={e => updateProject(p => ({ ...p, endings: p.endings.map(x => x.id === ending.id ? { ...x, body: e.target.value } : x) }))} />
                  </div>
                ))}
              </div>
            </section>
          )}
        </div>
      </main>

      {previewMode && (
        <div className="preview-overlay">
          <div className="preview-window">
            <div className="preview-bar">
              <div><span className="preview-live-dot" /> PREVIEW</div>
              <button onClick={() => setPreviewMode(false)}>닫기 ×</button>
            </div>
            <div className="preview-stage">
              {!previewScene ? (
                <div className="preview-ending-screen">
                  <div className="preview-ending-kicker">ENDING</div>
                  <h2>{project.endings.find(e => e.id === previewEndingId)?.name || 'END'}</h2>
                  <p>{project.endings.find(e => e.id === previewEndingId)?.body || '엔딩에 도달했어.'}</p>
                  <button className="dark-btn" onClick={() => { setPreviewSceneId(project.scenes[0]?.id || null); setPreviewBlockIndex(0); }}>처음부터</button>
                </div>
              ) : previewBlock?.type === 'dialogue' ? (
                <div className="visualnovel-preview">
                  <div className="preview-ghost-character" />
                  <div className="dialogue-box">
                    <div className="preview-speaker">{project.characters.find(c => c.id === previewBlock.speakerId)?.name || ''}</div>
                    <div className="preview-text">{previewBlock.text || ' '}</div>
                    <button className="next-arrow" onClick={() => setPreviewBlockIndex(i => i + 1 < previewScene.blocks.length ? i + 1 : 0)}>›</button>
                  </div>
                </div>
              ) : previewBlock?.type === 'choice' ? (
                <div className="choice-preview">
                  <div className="choice-preview-prompt">{previewBlock.prompt || '선택하세요.'}</div>
                  {(previewBlock.options || []).map(option => (
                    <button key={option.id} className="preview-choice" onClick={() => goPreviewNext(option.targetId)}>{option.text || '선택지'}</button>
                  ))}
                </div>
              ) : (
                <div className="preview-empty">더 진행할 내용이 없어.</div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;
